// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUpdateChange } from "./FileUpdateChange";

export type FileChangePatchDeltaNotification = { threadId: string, turnId: string, itemId: string, activePath: string | null, changes: Array<FileUpdateChange>, };
